### ISSUE TITLE
023 - Actualizar los estados de los Trails automáticamente

### ISSUE THREAD

**Issue by jvegax** [GameTrail/gametrail-front#102]
Cuando todos los juegos estén completos que el trail se actualice a COMPLETADO, mientras no esté completado, se muestra en PROGRESO

Sólo el Owner del Trail puede cambiar los estados de los juegos

**Comment by ddiazlop** [comment]
```
const UserTrailList:FC<Props> = ({ trailList }) => {
  const { t } = useLanguage();
  const router = useRouter();
  const handleRenderStatus = (trail: Trail) => {
    const status = Date.parse(trail.finishDate) > new Date().getTime();
    return status
      ? <span style={{ backgroundColor: theme.nord.blue2 }}>{t('trail_in_progress')}</span>
      : <span style={{ backgroundColor: theme.nord.green }}>{t('trail_finished')}</span>;
  };
```


Ya se cierra automáticamente una vez termina la fecha, forzar su cierre quizá no es conveniente ya que podrían los usuarios usarlo para abrir y cerrar trails constantemente. Mejor que se ponga en finalizado según la fecha como está y ya.
